STAC-22210 Throw if not empty

diff --git a/.github/actions/changeset-status/action.yml b/.github/actions/changeset-status/action.yml
--- a/.github/actions/changeset-status/action.yml
+++ b/.github/actions/changeset-status/action.yml
@@ -48,11 +48,11 @@ runs:
 
           echo "$CAUGHT_ERROR"
 
-          # if ! echo "$CAUGHT_ERROR" | grep -q "Some packages have been changed but no changesets were found"; then
-          #   # if the error is not caused by empty changesets, print the error and exit
-          #   echo "$CAUGHT_ERROR"
-          #   exit 1
-          # fi
+          # If the error is NOT caused by empty changesets, print the error and exit
+          if ! echo "$CAUGHT_ERROR" | grep -q "Some packages have been changed but no changesets were found"; then
+            echo "$CAUGHT_ERROR"
+            exit 1
+          fi
         }
 
         # if the .releases length is greater than 0, then the changeset is ready to be released
