STAC-22210 Print error

diff --git a/.github/actions/changeset-status/action.yml b/.github/actions/changeset-status/action.yml
--- a/.github/actions/changeset-status/action.yml
+++ b/.github/actions/changeset-status/action.yml
@@ -44,7 +44,15 @@ runs:
         { # try
           yarn changeset status ${{ inputs.args }} --output $RELATED_OUTPUT 2>&1
         } || { # catch
-          echo 'oops, error'
+          CAUGHT_ERROR=$(cat /dev/stderr)
+
+          echo "$CAUGHT_ERROR"
+
+          # if ! echo "$CAUGHT_ERROR" | grep -q "Some packages have been changed but no changesets were found"; then
+          #   # if the error is not caused by empty changesets, print the error and exit
+          #   echo "$CAUGHT_ERROR"
+          #   exit 1
+          # fi
         }
 
         # if the .releases length is greater than 0, then the changeset is ready to be released
