STAC-22210 Update checks (#60)
* STAC-22210 Delete use of changed-files GH action

* STAC-22210 Satisfy eslint check

* STAC-22210 Rename .js to .ts

* STAC-22210 Introduce typecheck script

* STAC-22210 Add typecheck step to check workflow

* STAC-22210 Update changeset-status action

* STAC-22210 Bump upload/download-artefact actions

* STAC-22210 Add new version check

* STAC-22210 Drop --since

* STAC-22210 Print the output file

* STAC-22210 Print GH output

* STAC-22210 Do not supress changeset error

* STAC-22210 Use --since with BASE_BRANCH

* STAC-22210 Revert --since strategy

* STAC-22210 Update changesets/cli

* STAC-22210 Catch error and handle empty output

* STAC-22210 Add error to a var

* STAC-22210 Do not handle error

* STAC-22210 Print error

* STAC-22210 Throw if not empty

* STAC-22210 Add set -e

* STAC-22210 Set -e in shell:

* STAC-22210 Catch error directly from changeset

diff --git a/.github/actions/changeset-status/action.yml b/.github/actions/changeset-status/action.yml
--- a/.github/actions/changeset-status/action.yml
+++ b/.github/actions/changeset-status/action.yml
@@ -37,16 +37,22 @@ runs:
         fi
         echo "✅ Temporary file created at: $OUTPUT"
 
+        RELATED_OUTPUT=$(realpath --relative-to . "$OUTPUT")
+
         # Run the changeset status command with relative path output
-        yarn changeset status ${{ inputs.args }} --output $(realpath --relative-to . "$OUTPUT")
+        # and catch an error if the command fails
+        { # try
+          CAUGHT_OUTPUT=$(yarn changeset status ${{ inputs.args }} --output $RELATED_OUTPUT 2>&1)
+        } || { # catch
+          # If the error is NOT caused by empty changesets, print the error and exit
+          if ! echo "$CAUGHT_OUTPUT" | grep -q "Some packages have been changed but no changesets were found"; then
+            echo "$CAUGHT_OUTPUT" >&2
+            exit 1
+          fi
+        }
 
-        if [ ! -s "$OUTPUT" ]; then
-          echo "🚨 Error: Temporary file is empty after running 'yarn changeset status'"
-          exit 1
-        fi
-
-        # if the .releases length is greater than 0, then the changeset is ready to be released
-        if jq -e '.releases | length > 0' "$OUTPUT" > /dev/null; then
+        # if the output is not empty and the .releases length is greater than 0, then the changeset is ready to be released
+        if [ -s "$OUTPUT" ] && jq -e '.releases | length > 0' "$OUTPUT" > /dev/null; then
           NAME=$(jq -r '.releases[0].name' "$OUTPUT")
           TYPE=$(jq -r '.releases[0].type' "$OUTPUT")
           OLD_VERSION=$(jq -r '.releases[0].oldVersion' "$OUTPUT")
@@ -56,6 +62,10 @@ runs:
           echo "type=$TYPE" >> $GITHUB_OUTPUT
           echo "old_version=$OLD_VERSION" >> $GITHUB_OUTPUT
           echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
+
+          # print the github output
+          echo "📦 Changeset found:"
+          cat $GITHUB_OUTPUT
         else
           echo "⏩ No changeset found"
         fi
