STAC-22210 Revert --since strategy

diff --git a/.github/actions/changeset-status/action.yml b/.github/actions/changeset-status/action.yml
--- a/.github/actions/changeset-status/action.yml
+++ b/.github/actions/changeset-status/action.yml
@@ -1,5 +1,10 @@
 name: Read changeset status
 
+inputs:
+  args:
+    description: Additional arguments to pass to 'yarn changeset status'
+    required: false
+
 outputs:
   base_branch:
     description: The base branch of the changeset
@@ -24,9 +29,6 @@ runs:
       shell: bash
       id: status
       run: |
-        BASE_BRANCH=$(jq -r '.baseBranch' .changeset/config.json)
-        echo "base_branch=$BASE_BRANCH" >> $GITHUB_OUTPUT
-
         OUTPUT=$(mktemp "${{runner.temp}}/changeset-output.XXXXXX.json")
 
         if [ ! -f "$OUTPUT" ]; then
@@ -36,13 +38,15 @@ runs:
         echo "✅ Temporary file created at: $OUTPUT"
 
         # Run the changeset status command with relative path output
-        yarn changeset status --since "origin/$BASE_BRANCH" --output $(realpath --relative-to . "$OUTPUT")
+        yarn changeset status ${{ inputs.args }} --output $(realpath --relative-to . "$OUTPUT")
 
-        # The OUTPUT file might be empty, so the .releases value should default to an empty array.
-        # If the .releases value is empty, then the changeset is not ready to be released
-        if jq -e '(.releases // [] | length) == 0' "$OUTPUT" > /dev/null; then
-          echo "⏩ No changeset found"
-        else
+        if [ ! -s "$OUTPUT" ]; then
+          echo "🚨 Error: Temporary file is empty after running 'yarn changeset status'"
+          exit 1
+        fi
+
+        # if the .releases length is greater than 0, then the changeset is ready to be released
+        if jq -e '.releases | length > 0' "$OUTPUT" > /dev/null; then
           NAME=$(jq -r '.releases[0].name' "$OUTPUT")
           TYPE=$(jq -r '.releases[0].type' "$OUTPUT")
           OLD_VERSION=$(jq -r '.releases[0].oldVersion' "$OUTPUT")
@@ -56,4 +60,9 @@ runs:
           # print the github output
           echo "📦 Changeset found:"
           cat $GITHUB_OUTPUT
+        else
+          echo "⏩ No changeset found"
         fi
+
+        BASE_BRANCH=$(jq -r '.baseBranch' .changeset/config.json)
+        echo "base_branch=$BASE_BRANCH" >> $GITHUB_OUTPUT
