STAC-22210 Catch error and handle empty output

diff --git a/.github/actions/changeset-status/action.yml b/.github/actions/changeset-status/action.yml
--- a/.github/actions/changeset-status/action.yml
+++ b/.github/actions/changeset-status/action.yml
@@ -37,16 +37,22 @@ runs:
         fi
         echo "✅ Temporary file created at: $OUTPUT"
 
-        # Run the changeset status command with relative path output
-        yarn changeset status ${{ inputs.args }} --output $(realpath --relative-to . "$OUTPUT")
+        RELATED_OUTPUT=$(realpath --relative-to . "$OUTPUT")
 
-        if [ ! -s "$OUTPUT" ]; then
-          echo "🚨 Error: Temporary file is empty after running 'yarn changeset status'"
-          exit 1
-        fi
+        # Run the changeset status command with relative path output
+        # and catch an error if the command fails
+        {
+          yarn changeset status ${{ inputs.args }} --output $RELATED_OUTPUT 2>&1
+        } || {
+          if ! grep -q "Some packages have been changed but no changesets were found" /dev/stderr; then
+            # if the error is not caused by empty changesets, print the error and exit
+            cat /dev/stderr
+            exit 1
+          fi
+        }
 
         # if the .releases length is greater than 0, then the changeset is ready to be released
-        if jq -e '.releases | length > 0' "$OUTPUT" > /dev/null; then
+        if [ -s "$OUTPUT" ] && jq -e '.releases | length > 0' "$OUTPUT" > /dev/null; then
           NAME=$(jq -r '.releases[0].name' "$OUTPUT")
           TYPE=$(jq -r '.releases[0].type' "$OUTPUT")
           OLD_VERSION=$(jq -r '.releases[0].oldVersion' "$OUTPUT")
