Split Read Changesets Config step

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -65,36 +65,37 @@ jobs:
       - name: Build Observability Package
         run: yarn build-pkg observability
 
-      - name: Determine Release Details
-        id: release-details
-        # prevents this step from running on forks AND only on pushes and .changeset.baseBranch is the target branch
-        if: github.event_name == 'push'
+      - name: Read Changesets Config
+        id: changeset-config
         run: |
           BASE_BRANCH=$(jq -r '.baseBranch' .changeset/config.json)
 
-          echo "Base branch: $BASE_BRANCH"
+          echo "base_branch=$BASE_BRANCH" >> $GITHUB_OUTPUT
 
-          if [[ "$BASE_BRANCH" == "${{ github.ref_name }}" ]]; then
-            OUTPUT=$(mktemp ${{runner.temp}}/changeset-output.XXXXXX.json)
+      - name: Determine Release Details
+        id: release-details
+        # only on pushes and .changeset.baseBranch is the target branch
+        if: github.event_name == 'push' && steps.changeset-config.outputs.base_branch == github.ref_name
+        run: |
+          OUTPUT=$(mktemp ${{runner.temp}}/changeset-output.XXXXXX.json)
 
-            if [ ! -f "$OUTPUT" ]; then
-              echo "Failed to create temp file at: $OUTPUT"
-              exit 1
-            fi
-            echo "Temporary file created at: $OUTPUT"
-
-            # the status command uses path.join so the path should be relative
-            yarn changeset status --output $(realpath --relative-to . $OUTPUT)
-
-            if [ ! -s "$OUTPUT" ]; then
-              echo "Error: Temporary file is empty after running 'yarn changeset status'"
-              exit 1
-            fi
-
-            MESSAGE=$(jq -r 'if .releases | length > 0 then .releases[0] | "🚀 Release `\(.name)@\(.oldVersion) → \(.newVersion)`" else "Publishing release..." end' "$OUTPUT")
-
-            echo "message=$MESSAGE" >> $GITHUB_OUTPUT
+          if [ ! -f "$OUTPUT" ]; then
+            echo "Failed to create temp file at: $OUTPUT"
+            exit 1
           fi
+          echo "Temporary file created at: $OUTPUT"
+
+          # the status command uses path.join so the path should be relative
+          yarn changeset status --output $(realpath --relative-to . $OUTPUT)
+
+          if [ ! -s "$OUTPUT" ]; then
+            echo "Error: Temporary file is empty after running 'yarn changeset status'"
+            exit 1
+          fi
+
+          MESSAGE=$(jq -r 'if .releases | length > 0 then .releases[0] | "🚀 Release `\(.name)@\(.oldVersion) → \(.newVersion)`" else "Publishing release..." end' "$OUTPUT")
+
+          echo "message=$MESSAGE" >> $GITHUB_OUTPUT
 
       # creates a PR if there are changesets or assign the new tag if the PR is merged
       - name: Create Release Pull Request or Publish
